const allData = [

    {
        title: "Aankhon ki Gustaakhiyan",
        year: "2025",
        rating: "6.5",
        type: "Movie",
        genre: "Romance, Drama",
        cast: "Vikrant Massey, Shanaya kapoor",
        plot: "Explores the romance between two visually impaired characters, navigating both the joys and complexities of modern love.",
        poster: "https://i0.wp.com/urbanasian.com/wp-content/uploads/2025/06/5d07ce94-ef93-4854-979b-935aeec92a28.jpeg?resize=640%2C800&ssl=1",
        download_url: "https://new20.gdtot.dad/file/2427846448"
    },
    {
        title: "Superman",
        year: "2025",
        rating: "7.5",
        type: "Movie",
        genre: "Action, Adventure, Sci-Fi",
        cast: "Nathan Fillion, Nicholas Hoult, Rachel Brosnahan",
        plot: "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
        poster: "https://m.media-amazon.com/images/M/MV5BOGMwZGJiM2EtMzEwZC00YTYzLWIxNzYtMmJmZWNlZjgxZTMwXkEyXkFqcGc@._V1_.jpg",
        download_url: "https://new20.gdtot.dad/file/1327242675"
    },

    {
        title: "Housefull 5A",
        year: "2025",
        rating: "7.5",
        type: "Movie",
        genre: "Comedy, Family, Romance, Drama",
        cast: "Akshay Kumar, Riteish Deshmukh, jacqueline Fernandez, nana Patekar",
        plot: "Housefull 5 has been released in 2 versions, Housefull 5A and 5B. Both have different climaxes, different killers and different endings. The first two hours are the same in both versions, but the last 20 minutes differ.",
        poster: "https://images.fandango.com/ImageRenderer/0/0/redesign/static/img/default_poster--dark-mode.png/0/images/masterrepository/Fandango/240756/housefull5-9x16_Overseas.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=1u6o80f-32XrmTxvbePkwYlRrI468dF01&export=download&authuser=0"
    },
    {
        title: "Housefull 5B",
        year: "2025",
        rating: "7.5",
        type: "Movie",
        genre: "Comedy, Family, Romance, Drama",
        cast: "Akshay Kumar, Riteish Deshmukh, jacqueline Fernandez, nana Patekar",
        plot: "Housefull 5 has been released in 2 versions, Housefull 5A and 5B. Both have different climaxes, different killers and different endings. The first two hours are the same in both versions, but the last 20 minutes differ.",
        poster: "https://images.fandango.com/ImageRenderer/0/0/redesign/static/img/default_poster--dark-mode.png/0/images/masterrepository/Fandango/240756/housefull5-9x16_Overseas.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=1zyvp66M0TrT5x_eiHmvXpgqythGshRTF&export=download&authuser=0"
    },
    {
        title: "Maalik",
        year: "2025",
        rating: "7.5",
        type: "Movie",
        genre: "Action, Drama, Thriller",
        cast: " Rajkummar Rao, Saurabh Shukla, Swanand Kirkire",
        plot: "Set in the rural, rusty and politically charged Allahabad of the 1980s, Maalik is a peek into the making of a dreaded gangster from a humble background with intoxication of power to rule the world.",
        poster: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202408/rajkummar-rao-in-maalik-315843439-3x4.jpg?VersionId=vbGtcSEdPCIggRMEMZ3kPKRzN17l8a6m",
        download_url: "https://drive.usercontent.google.com/download?id=1JfxjpT2X0TiBGUtgsagVdtNzSHZd5wam&export=download&authuser=0"
    },
    {
        title: "Metro In Dino",
        year: "2025",
        rating: "7.5",
        type: "Movie",
        genre: "Comedy, Family, Romance, Drama",
        cast: "Aditya Roy Kapur, Sara Ali Khan, Anupam Kher, Neena Gupta",
        plot: "A modern take on love and relationships, exploring the lives of various characters in a bustling city.",
        poster: "https://static.toiimg.com/photo/122200827.cms?imgsize=139294",
        download_url: "https://drive.usercontent.google.com/download?id=1LL3mHomaOh4NL4JTOIcmKYQMjaWZTEUs&export=download&authuser=5"
    },
    {
        title: "Jurassic World Rebirth",
        year: "2025",
        rating: "8.5",
        type: "Movie",
        genre: "Action, Adventure, Sci-Fi",
        cast: "Chris Pratt, Bryce Dallas Howard, Sam Neill",
        plot: "In a world where dinosaurs roam freely, humanity must find a way to coexist with these ancient creatures while facing new threats.",
        poster: "https://image.tmdb.org/t/p/original/qwOwDHUPCcDRmdQu8dWCzIVMEgu.jpg",
        download_url: "https://new20.gdtot.dad/file/1265148599"
    },
    {
        title: "Sitaare Zameen Par",
        year: "2025",
        rating: "7.9",
        type: "Movie",
        genre: "Drama, Family, comedy",
        cast: "Aamir Khan, Darsheel Safary, Tanay Chheda",
        plot: "A disgraced basketball coach is given the chance to coach a team of players who are intellectually disabled, and soon realizes they just might have what it takes to make it to the national championships.",
        poster: "https://images.filmibeat.com/ph-big/2025/05/sitaare-zameen-par1747294849_1.jpg",
        download_url: "https://new20.gdtot.dad/file/1277221024"
    },
    {
        title: "Thug Life",
        year: "2025",
        rating: "7.5",
        type: "Movie",
        genre: "Drama, Crime, Thriller",
        cast: "Kamal Haasan, Nassar, Silambarasan, Trisha Krishnan",
        plot: "In a world ruled by crime and betrayal, mafia kingpin Sakthivel and his brother Manickam rescue a young boy, Amaran, during a violent police shootout and raise him as their own.",
        poster: "https://media.senscritique.com/media/000022852235/300/thug_life.jpg",
        download_url: "https://new20.gdtot.dad/file/1827055186"
    },
    {
        title: "Kannappa",
        year: "2025",
        rating: "7.5",
        type: "Movie",
        genre: "Drama, Action, Mythology",
        cast: "Prabhas, Preity Mukhundhan, Vishnu Manchu",
        plot: "After witnessing the cruel sacrifice of his childhood friend, an atheist warrior rejects religion until love forces him to find his own faith.",
        poster: "https://akm-img-a-in.tosshub.com/indiatoday/styles/medium_crop_simple/public/2023-11/f_kn7jpaoaa9lgw.jpg?VersionId=DtWS9SGrkn402eMgVUtYg9DzrGaN4E9f&size=750:*",
        download_url: "https://new20.gdtot.dad/file/1481040319"
    },
    {
        title: "Maa",
        year: "2025",
        rating: "7.1",
        type: "Movie",
        genre: "Horror, Thriller",
        cast: "Kajol, Kherin Sharma, Ronit Roy",
        plot: "A mother and daughter encounter a demon in a village where girls have been disappearing.",
        poster: "https://m.media-amazon.com/images/M/MV5BZjI1ZTUyYzItZDEyMy00MTE1LWFhZmMtZWUxOThjMjU5Njk1XkEyXkFqcGc@._V1_.jpg",
        download_url: "https://new20.gdtot.dad/file/2242209494"
    },

    {
        title: "Raid 2",
        year: "2025",
        rating: "7.5",
        type: "Movie",
        genre: "Action, Crime, Drama",
        cast: "Ajay Devgn, Ritesh Deshmukh, Vaani Kapoor",
        plot: "After exposing corruption, the protagonist must go deeper into the underworld.",
        poster: "https://tse3.mm.bing.net/th/id/OIP.u1WlBRRAiYdCuii6NgCtsgHaE8?pid=Api",
        download_url: "https://drive.usercontent.google.com/download?id=1v52WMVypfzvjOQYNBNzbOE2FO_oqL2mx&export=download&authuser=0"
    },
    {
        id: 2,
        title: "Alice in Borderland S01",
        year: "2020",
        rating: "8.7",
        type: "series",
        genre: "Action & Adventure, Drama, Mystery, Sci-Fi & Fantasy, Thriller",
        cast: "Kento Yamazaki, Tao Tsuchiya, Nijirô Murakami",
        plot: "A boy disappears, leading to supernatural mysteries and secret experiments.",
        poster: "https://upload.wikimedia.org/wikipedia/en/7/75/Alice_in_Borderland_poster.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=1k-l5v34Bhnyy3FD4XBXTmW-N5R-cVSeG&export=download&authuser=0"
    },
    {
        id: 3,
        title: "Alice in Borderland S02",
        year: "2022",
        rating: "8.7",
        type: "series",
        genre: "Action & Adventure, Drama, Mystery, Sci-Fi & Fantasy, Thriller",
        cast: "Kento Yamazaki, Tao Tsuchiya, Nijirô Murakami",
        plot: "A boy disappears, leading to supernatural mysteries and secret experiments.",
        poster: "https://upload.wikimedia.org/wikipedia/en/7/75/Alice_in_Borderland_poster.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=147QDGJv8BnqJT6ReesVjtIh1BGM_WOZX&export=download&authuser=0"
    },
    {
        id: 1,
        title: "Padmaavat",
        year: 2018,
        rating: "7.7/10",
        genre: "Biography, Drama, History",
        poster: "https://image.tmdb.org/t/p/w500/dtIceHDioZP4oHAmhHlWmDuZEM9.jpg",
        plot: "Set in medieval Rajasthan, Queen Padmavati is married to Maharawal Ratan Singh. The kingdom is invaded by Alauddin Khilji, who becomes obsessed with Padmavati's beauty.",
        director: "Sanjay Leela Bhansali",
        cast: "Deepika Padukone, Shahid Kapoor, Ranveer Singh",
        runtime: "164 min",
        detail: "must watch",
        type: "Movie",
        download_url: "https://drive.usercontent.google.com/download?id=1tFaFdCtY1K_JcvcGJwxesYyuTYfdGcl3&export=download&authuser=0"
    },
    {
        title: "Inception",
        year: "2010",
        rating: "8.8",
        type: "Movie",
        detail: "must watch",
        genre: "Action, Sci-Fi",
        cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
        plot: "A thief who uses dream-sharing tech is given the inverse task of planting an idea.",
        poster: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=1yof0tCINz37iEmKb7EQak9p1FRaLJJjl&export=download&authuser=0"
    },
    {
        id: 3,
        title: "The Martian",
        year: 1994,
        rating: "8.9/10",
        detail: "must watch",
        genre: "sci-fi, Drama",
        poster: "https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg",
        plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        director: "Quentin Tarantino",
        cast: "John Travolta, Uma Thurman, Samuel L. Jackson",
        runtime: "154 min",
        language: "English",
        type: "Movie",
        download_url: "https://drive.usercontent.google.com/download?id=1cU4gl6GvHJllEmPW7miyipe_8ULnOPjU&export=download&authuser=0"
    },
    {
        title: "Mukkabaaz",
        year: "2018",
        rating: "7.8",
        type: "Movie",
        detail: "must watch",
        genre: "Action, Drama, Sport",
        cast: "Vineet Kumar Singh, Zoya Hussain, Ravi Kishan",
        plot: "A low caste boxer trains at a gym controlled by a local Don. Shravan falls for Mishra’s niece. The Don does not approve of this match. Shravan strives to win Sunaina’s hand in marriage and become a successful boxer while trying to avoid retaliation from the Don.",
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/mukkabaaz-et00059419-07-07-2017-05-57-42.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=1W3fDQXUREvs6-zdywBzEwlrfdL9IOB-E&export=download&authuser=0"
    },
    {
        title: "Adipurush",
        year: "2023",
        rating: "7.8",
        type: "Movie",
        genre: "Action, Adventure, Drama",
        cast: "Prabhas, Kriti Sanon, Saif Ali Khan",
        plot: "A mythological epic based on the Ramayana, depicting the battle between Lord Rama and Ravana.",
        poster: "https://filmfare.wwmindia.com/content/2022/sep/adipurush-poster-first-look.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=10LDY_CgQ59y4lbgT3-a_vzjTmRcMYYf5&export=download&authuser=0"
    },

]
