const allData = [
    {
        title: "Raid 2",
        year: "2025",
        rating: "7.5",
        type: "Movie",
        genre: "Action, Crime, Drama",
        cast: "Ajay Devgn, Ritesh Deshmukh, Vaani Kapoor",
        plot: "After exposing corruption, the protagonist must go deeper into the underworld.",
        poster: "https://tse3.mm.bing.net/th/id/OIP.u1WlBRRAiYdCuii6NgCtsgHaE8?pid=Api",
        download_url: "https://drive.usercontent.google.com/download?id=1v52WMVypfzvjOQYNBNzbOE2FO_oqL2mx&export=download&authuser=0"
    },
    {
        id: 2,
        title: "Alice in Borderland S01",
        year: "2020",
        rating: "8.7",
        type: "series",
        genre: "Action & Adventure, Drama, Mystery, Sci-Fi & Fantasy, Thriller",
        cast: "Kento Yamazaki, Tao Tsuchiya, Nijirô Murakami",
        plot: "A boy disappears, leading to supernatural mysteries and secret experiments.",
        poster: "https://upload.wikimedia.org/wikipedia/en/7/75/Alice_in_Borderland_poster.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=1k-l5v34Bhnyy3FD4XBXTmW-N5R-cVSeG&export=download&authuser=0"
    },
    {
        id: 3,
        title: "Alice in Borderland S02",
        year: "2022",
        rating: "8.7",
        type: "series",
        genre: "Action & Adventure, Drama, Mystery, Sci-Fi & Fantasy, Thriller",
        cast: "Kento Yamazaki, Tao Tsuchiya, Nijirô Murakami",
        plot: "A boy disappears, leading to supernatural mysteries and secret experiments.",
        poster: "https://upload.wikimedia.org/wikipedia/en/7/75/Alice_in_Borderland_poster.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=147QDGJv8BnqJT6ReesVjtIh1BGM_WOZX&export=download&authuser=0"
    },
    {
        id: 1,
        title: "Padmaavat",
        year: 2018,
        rating: "7.7/10",
        genre: "Biography, Drama, History",
        poster: "https://image.tmdb.org/t/p/w500/dtIceHDioZP4oHAmhHlWmDuZEM9.jpg",
        plot: "Set in medieval Rajasthan, Queen Padmavati is married to Maharawal Ratan Singh. The kingdom is invaded by Alauddin Khilji, who becomes obsessed with Padmavati's beauty.",
        director: "Sanjay Leela Bhansali",
        cast: "Deepika Padukone, Shahid Kapoor, Ranveer Singh",
        runtime: "164 min",
        detail: "must watch",
        type: "Movie",
        download_url: "https://drive.usercontent.google.com/download?id=1tFaFdCtY1K_JcvcGJwxesYyuTYfdGcl3&export=download&authuser=0"
    },
    {
        title: "Inception",
        year: "2010",
        rating: "8.8",
        type: "Movie",
        detail: "must watch",
        genre: "Action, Sci-Fi",
        cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
        plot: "A thief who uses dream-sharing tech is given the inverse task of planting an idea.",
        poster: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=1yof0tCINz37iEmKb7EQak9p1FRaLJJjl&export=download&authuser=0"
    },
    {
        id: 3,
        title: "The Martian",
        year: 1994,
        rating: "8.9/10",
        detail: "must watch",
        genre: "sci-fi, Drama",
        poster: "https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg",
        plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        director: "Quentin Tarantino",
        cast: "John Travolta, Uma Thurman, Samuel L. Jackson",
        runtime: "154 min",
        language: "English",
        type: "Movie",
        download_url: "https://drive.usercontent.google.com/download?id=1cU4gl6GvHJllEmPW7miyipe_8ULnOPjU&export=download&authuser=0"
    },
    {
        title: "Mukkabaaz",
        year: "2018",
        rating: "7.8",
        type: "Movie",
        detail: "must watch",
        genre: "Action, Drama, Sport",
        cast: "Vineet Kumar Singh, Zoya Hussain, Ravi Kishan",
        plot: "A low caste boxer trains at a gym controlled by a local Don. Shravan falls for Mishra’s niece. The Don does not approve of this match. Shravan strives to win Sunaina’s hand in marriage and become a successful boxer while trying to avoid retaliation from the Don.",
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/mukkabaaz-et00059419-07-07-2017-05-57-42.jpg",
        download_url: "https://drive.usercontent.google.com/download?id=1W3fDQXUREvs6-zdywBzEwlrfdL9IOB-E&export=download&authuser=0"
    },
]